export const TRADE_TEMPLATES: Record<string, { description: string; amount: number }[]> = {
  plumber: [
    { description: 'Service call (first hour)', amount: 150 },
    { description: 'Additional labour (per hour)', amount: 110 },
    { description: 'Blocked drain clearance', amount: 280 },
    { description: 'Hot water system service', amount: 220 },
    { description: 'Tap repair (washer replacement)', amount: 95 },
    { description: 'Toilet repair (cistern parts)', amount: 180 },
    { description: 'After-hours callout fee', amount: 250 },
    { description: 'Materials & parts (variable)', amount: 0 },
  ],
  electrician: [
    { description: 'Service call (first hour)', amount: 160 },
    { description: 'Additional labour (per hour)', amount: 120 },
    { description: 'Power point installation', amount: 145 },
    { description: 'Light fitting installation', amount: 95 },
    { description: 'Ceiling fan installation', amount: 195 },
    { description: 'Switchboard upgrade', amount: 1850 },
    { description: 'Safety switch installation', amount: 280 },
    { description: 'After-hours callout fee', amount: 280 },
  ],
  builder: [
    { description: 'Site inspection & quote', amount: 0 },
    { description: 'Labour (per day)', amount: 850 },
    { description: 'Apprentice labour (per day)', amount: 450 },
    { description: 'Project management fee', amount: 0 },
    { description: 'Materials supply (variable)', amount: 0 },
    { description: 'Skip bin hire', amount: 450 },
    { description: 'Permit & approval fees', amount: 0 },
  ],
  painter: [
    { description: 'Interior wall painting (per sqm)', amount: 18 },
    { description: 'Exterior painting (per sqm)', amount: 28 },
    { description: 'Ceiling painting (per sqm)', amount: 15 },
    { description: 'Trim & doors (per door)', amount: 65 },
    { description: 'Surface preparation & sanding', amount: 0 },
    { description: 'Premium paint upgrade', amount: 0 },
    { description: 'Drop sheets & masking', amount: 0 },
  ],
  carpenter: [
    { description: 'Labour (per hour)', amount: 95 },
    { description: 'Apprentice labour (per hour)', amount: 50 },
    { description: 'Site measure & quote', amount: 0 },
    { description: 'Custom timber supply', amount: 0 },
    { description: 'Door hanging', amount: 220 },
    { description: 'Skirting installation (per metre)', amount: 35 },
    { description: 'Decking (per sqm)', amount: 180 },
  ],
  landscaper: [
    { description: 'Site assessment & design', amount: 280 },
    { description: 'Labour (per day, 2 staff)', amount: 1200 },
    { description: 'Turf supply & installation (per sqm)', amount: 22 },
    { description: 'Retaining wall (per linear metre)', amount: 320 },
    { description: 'Mulch supply & spread (per cubic m)', amount: 95 },
    { description: 'Plant supply (variable)', amount: 0 },
    { description: 'Green waste removal', amount: 280 },
  ],
  tiler: [
    { description: 'Floor tiling (per sqm)', amount: 75 },
    { description: 'Wall tiling (per sqm)', amount: 85 },
    { description: 'Waterproofing (per sqm)', amount: 35 },
    { description: 'Tile removal & disposal (per sqm)', amount: 45 },
    { description: 'Grout & adhesive', amount: 0 },
    { description: 'Tile supply (variable)', amount: 0 },
    { description: 'Silicone & finishing', amount: 65 },
  ],
  roofer: [
    { description: 'Roof inspection & report', amount: 280 },
    { description: 'Tile replacement (per tile)', amount: 35 },
    { description: 'Gutter cleaning (per metre)', amount: 12 },
    { description: 'Gutter replacement (per metre)', amount: 85 },
    { description: 'Roof restoration (per sqm)', amount: 45 },
    { description: 'Ridge capping repointing (per metre)', amount: 55 },
    { description: 'Roof access scaffolding', amount: 450 },
  ],
  concreter: [
    { description: 'Concrete slab (per sqm)', amount: 165 },
    { description: 'Driveway (per sqm)', amount: 145 },
    { description: 'Site preparation & excavation', amount: 0 },
    { description: 'Reinforcement mesh & steel', amount: 0 },
    { description: 'Decorative finish upgrade', amount: 0 },
    { description: 'Concrete pump hire', amount: 850 },
  ],
  fencer: [
    { description: 'Colorbond fencing (per linear metre)', amount: 110 },
    { description: 'Timber paling fence (per linear metre)', amount: 95 },
    { description: 'Gate installation (single)', amount: 450 },
    { description: 'Old fence removal (per metre)', amount: 25 },
    { description: 'Concrete footings (per post)', amount: 45 },
    { description: 'Site measure & quote', amount: 0 },
  ],
  cleaner: [
    { description: 'Regular clean (per hour)', amount: 55 },
    { description: 'Deep clean (per hour)', amount: 75 },
    { description: 'End of lease clean (2 bed)', amount: 380 },
    { description: 'End of lease clean (3 bed)', amount: 480 },
    { description: 'Carpet steam clean (per room)', amount: 65 },
    { description: 'Window cleaning (per window)', amount: 12 },
    { description: 'Oven & rangehood deep clean', amount: 145 },
  ],
  hvac: [
    { description: 'Service call (first hour)', amount: 170 },
    { description: 'Additional labour (per hour)', amount: 130 },
    { description: 'Split system installation (single head)', amount: 1850 },
    { description: 'Ducted system service', amount: 380 },
    { description: 'Filter replacement', amount: 95 },
    { description: 'Refrigerant top-up', amount: 250 },
    { description: 'After-hours callout fee', amount: 290 },
  ],
}